{% set name = "prettyprinter" %}
{% set version = "0.18.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/prettyprinter-{{ version }}.tar.gz
  sha256: 9fe5da7ec53510881dd35d7a5c677ba45f34cfe6a8e78d1abd20652cf82139a8

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - pytest-runner ==3.0
    - python {{ python_min }}
  run:
    - colorful >=0.4.0
    - pygments >=2.2.0
    - python >={{ python_min }}

test:
  imports:
    - prettyprinter
    - prettyprinter.extras
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/tommikaikkonen/prettyprinter
  summary: Syntax-highlighting, declarative and composable pretty printer for Python 3.5+
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - asford
